<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><title>Laporan Tagihan Sandbox</title><style>
    @page{margin:28px}body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#172b4d}h1{font-size:18px;margin:0 0 5px}h2{font-size:13px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccd5e0;padding:6px}th{background:#123d72;color:#fff}thead{display:table-header-group}tr{page-break-inside:avoid}.notice{background:#fff2d5;padding:10px;margin:12px 0}.right{text-align:right}
</style></head><body>
<h1>STTMI — Laporan Tagihan Mahasiswa</h1><p>Sekolah Tinggi Teknologi Mineral Indonesia &middot; Dicetak {{ now()->format('d/m/Y H:i') }}</p>
<div class="notice"><strong>SANDBOX / SIMULASI — BUKAN PEMBAYARAN NYATA</strong></div>
@php($active = $bills->where('status','!=','dibatalkan'))
@php($paidTransactions = $active->flatMap(fn ($bill) => $bill->pembayaran)->where('status','paid'))
@php($paidVa = $paidTransactions->filter(fn ($p) => $p->metode_pembayaran === 'va_midtrans' || ($p->metode_pembayaran === null && $p->source === 'midtrans')))
@php($paidCash = $paidTransactions->filter(fn ($p) => $p->metode_pembayaran === 'cash' || in_array($p->source,['cash','manual'],true)))
<p>Total tagihan aktif: Rp {{ number_format($active->sum('total_tagihan'),0,',','.') }} &nbsp; | &nbsp; VA: Rp {{ number_format($paidVa->sum('amount'),0,',','.') }} &nbsp; | &nbsp; Cash: Rp {{ number_format($paidCash->sum('amount'),0,',','.') }} &nbsp; | &nbsp; Biaya layanan: Rp {{ number_format($paidTransactions->sum('biaya_layanan'),0,',','.') }} &nbsp; | &nbsp; Sisa: Rp {{ number_format($active->sum('sisa_tagihan'),0,',','.') }}</p>
<table><thead><tr><th>No</th><th>NIM / Nama</th><th>Kode / Jenis</th><th>Pokok</th><th>Total</th><th>VA</th><th>Cash</th><th>Biaya</th><th>Sisa</th><th>Metode / Referensi</th><th>Status</th></tr></thead><tbody>
@forelse($bills as $bill)@php($paid = $bill->pembayaran)@php($va = $paid->filter(fn ($p) => $p->metode_pembayaran === 'va_midtrans' || ($p->metode_pembayaran === null && $p->source === 'midtrans')))@php($cash = $paid->filter(fn ($p) => $p->metode_pembayaran === 'cash' || in_array($p->source,['cash','manual'],true)))<tr><td>{{ $loop->iteration }}</td><td>{{ $bill->mahasiswa?->nim }}<br>{{ $bill->mahasiswa?->nama }}</td><td>{{ $bill->kode_tagihan }}<br>{{ $bill->jenis_tagihan }}</td><td class="right">{{ number_format($bill->nominal_pokok,0,',','.') }}</td><td class="right">{{ number_format($bill->total_tagihan,0,',','.') }}</td><td class="right">{{ number_format($va->sum('amount'),0,',','.') }}</td><td class="right">{{ number_format($cash->sum('amount'),0,',','.') }}</td><td class="right">{{ number_format($paid->sum('biaya_layanan'),0,',','.') }}</td><td class="right">{{ number_format($bill->sisa_tagihan,0,',','.') }}</td><td>{{ $paid->map(fn ($p) => $p->metode_label.': '.($p->nomor_referensi ?: $p->external_id))->implode('; ') ?: '-' }}</td><td>{{ ucwords(str_replace('_',' ',$bill->status_tampil)) }}</td></tr>@empty<tr><td colspan="11">Tidak ada tagihan untuk filter ini.</td></tr>@endforelse
</tbody></table></body></html>
